Implements 3d text feature for engine
acgaudette/nmg-vulkan pull request #22
Opened 2018-07-26 03:54 UTC by hobogenized

- Contains stubs for 2d text for when it will be added
- Allows for text to be added to scenes

2018-07-26 15:02 UTC, acgaudette commented
Reason for new dependencies: `rand`, `image`?

2018-07-26 15:12 UTC, acgaudette commented
Getting a `DEBUG_REPORT: Object: VK_NULL_HANDLE (Type = 0) | Type mismatch on descriptor slot 0.1 (used as type `ptr to const uniform sampler+image(dim=1, sampled=1)`) but descriptor of type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC`

2018-07-26 15:16 UTC, acgaudette commented
Re: component names. How about `label` for text2d and `text` for text3d? I'm not sold, but might be better than what we have. jw

2018-07-26 16:15 UTC, acgaudette requested changes
See comments.
Need `text.rs` to be documented more until I can really comment.
Did a quick pass of render, in general looks good but seems like you still have a number of TODOs floating around. Make sure you're taking care of memory and concurrency issues.

2018-07-26 16:15 UTC, acgaudette commented on src/font.rs
> +fn parse_bmchar<'a>(full_str: &'a str) -> Bmchar {
This is a good place for proper error handling + maybe a variable macro.

2018-07-26 16:15 UTC, acgaudette commented on src/font.rs
> +                Some("info") => {
Can get rid of the long comment. Maybe could use the info `face` at least to log the font we're loading.

2018-07-26 16:15 UTC, acgaudette commented on src/components/mod.rs
> +    pub text3ds:    text3d::Manager,
Re: component names. How about label for text2d and text for text3d? I'm not sold, but might be better than what we have. jw

2018-07-26 16:15 UTC, acgaudette commented on Cargo.toml
> +image = "0.19.0"
Reason for new dependencies: `rand`, `image`?

2018-07-26 16:15 UTC, acgaudette commented on examples/text.rs
> +        let object_0 = entities.add();
Text example probably doesn't actually need all the extra rendering

2018-07-26 16:15 UTC, acgaudette commented on shaders/font3d.frag
> +
Don't need this spacing here

2018-07-26 16:15 UTC, acgaudette commented on src/lib.rs
> +        if let Err(e) = context.draw(
You probably want
```
if let Err(e) = context.draw(
    &components.draws.instances,
    &mut components.text3ds,
) {
```

2018-07-26 16:15 UTC, acgaudette commented on src/components/text3d.rs
> +use font::*;
I usually prefer not to do this, but maybe you have a good reason (`font::*`)

2018-07-26 16:15 UTC, acgaudette commented on src/components/text3d.rs
> +    // Update point light positions from transform component
Comment?

2018-07-26 16:15 UTC, acgaudette commented on src/components/text.rs
> +}
The no EOLs in some of your files are a bit weird

2018-07-26 16:15 UTC, acgaudette commented on src/components/text.rs
> +extern crate fnv;
It is strange that this file is in `components`--should probably be one level up

2018-07-26 16:15 UTC, acgaudette commented on src/components/text.rs
> +// TODO: Implement add_text functionality from render
Is this comment still valid?

2018-07-26 16:15 UTC, acgaudette commented on src/components/text.rs
> +pub fn prepare_bitmap_text(
Some more verbose commenting would be helpful in this file

2018-07-26 16:15 UTC, acgaudette commented on src/components/text3d.rs
> +    //TODO: Implement add_text functionality from render
Why is this fn wrapped again?

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> +    text_3d:          TextDisplay,
The ordering is potentially strange here? (text after the persistent data)

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> +    ) -> vd::Result<Context<'a>> {
New lifetimes?

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> +
Watch out for this whitespace

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> +        let font_path = config::load_section_setting::<String>(
This all probably belongs a bit higher up, with a `/* Text */` header or something (should be above debug and the command buffers at least)

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> -        self.render_pass = render_pass;
It looks like you've made some changes to the base `render.rs` along with the new text code. If you could split up any changes to a separate commit, that would be great.

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> +    //TODO: Change to setting for use with RenderDoc
? Artifact

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> -
Try to remove diffs like this which are just changing the original file

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> +    //eprintln!("Width: {}", extent2d.width());
?

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> +    println!("Loading {}d text shaders from \"{}\"", type_shader, path);
If you're going to add this message, we should probably add one for the debug shaders as well

2018-07-26 16:15 UTC, acgaudette commented on src/render.rs
> +    //TODO: Clean up buffers
Watch out

2018-08-19 16:50 UTC, hobogenized commented on src/lib.rs
> +        if let Err(e) = context.draw(
Done

2018-08-19 21:33 UTC, acgaudette commented
Getting error: `DEBUG_REPORT:  [ UNASSIGNED-CoreValidation-Shader-DescriptorTypeMismatch ] Object: VK_NULL_HANDLE (Type = 0) | Type mismatch on descriptor slot 0.1 (expected `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`) but descriptor of type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC` @hobogenized

2018-08-19 21:56 UTC, acgaudette approved these changes

2018-08-19 21:56 UTC, acgaudette commented on src/components/text.rs
> +    ptr: *mut *mut render::FontData,
Do both of these pointers need to be mutable?

2018-08-19 21:57 UTC, closed without merging