Implement label/screenspace text
acgaudette/nmg-vulkan pull request #28
Opened 2018-10-17 04:02 UTC by hobogenized

- Switch to free license Caladea font
- Change text example to demonstrate difference between label and text
- Enforce that texture for font exists at same root as font data file
- Change 2d font shader to allow for transforms
- Remove references to models

2018-10-17 13:02 UTC, acgaudette requested changes

2018-10-17 13:02 UTC, acgaudette commented on shaders/font2d.vert
> +    gl_Position = model_data.model * vec4(inPos, 1.0);
Maybe comment exactly what's going on lines 19-21

2018-10-17 13:02 UTC, acgaudette commented on shaders/font2d.vert
> +} model_data;
I might call this `instance` instead of `model_data`

2018-10-17 13:02 UTC, acgaudette commented on shaders/font2d.vert
>  layout (location = 0) in vec3 inPos;
Consider making this a `vec2` (and updating the requisite code in the renderer). You could still use the transform component with no issues, but wherever you load the actual position data, you could use an `alg::Vec2` instead. Are you using the z for anything?

2018-10-17 13:02 UTC, acgaudette commented on src/components/label.rs
> +    pub fn pixel_scale_factor(&mut self, scale_factor: f32) -> &mut TextBuilder<'a> {
May as well add some doc comments on `pixel_scale_factor` and `aspect_scale_factor` explaining what they are.

2018-10-17 13:02 UTC, acgaudette commented on src/components/label.rs
> +
```suggestion
```

2018-10-17 13:02 UTC, acgaudette commented on src/components/label.rs
> +    #[cfg(debug_assertions)] fn debug_name(&self) -> &str { "Text" }
```suggestion
    #[cfg(debug_assertions)] fn debug_name(&self) -> &str { "Label" }
```

2018-10-17 13:02 UTC, acgaudette commented on src/components/label.rs
> +            let font_ubo = render::FontUBO {
It's a bit confusing here that the actual model matrix gets put into a font UBO that is then pushed into a vec of "model matrices." Perhaps could rename `model_matrices` to `uniform_data` or `instance_data`.

If you go down this path, it would be a good idea to do it for the text component as well.

2018-10-17 13:02 UTC, acgaudette commented on src/components/mod.rs
> +    pub transforms:     transform::Manager,
Looks like something weird happened here with the spacing.

2018-10-17 13:02 UTC, acgaudette commented on src/components/text_overlay.rs
> +extern crate fnv;
Is this file necessary?

2018-10-17 13:02 UTC, acgaudette commented on src/render.rs
> +        /*
What's going on here?

2018-10-17 13:02 UTC, acgaudette commented on src/render.rs
>      let image_memory_barrier = image_memory_barrier_builder
```suggestion

    let image_memory_barrier = image_memory_barrier_builder
```

2018-10-17 13:02 UTC, acgaudette commented on src/components/label.rs
> +
```suggestion

```

2018-10-17 13:02 UTC, acgaudette commented on examples/text.rs
> +        /* Point light */
Note that your font shaders are currently not computing lighting.

2018-10-17 13:02 UTC, acgaudette commented on examples/text.rs
> +            alg::Quat::axis_angle_raw(alg::Vec3::up(), -angle)
To be honest, I'd prefer it if we only keep the second rotation (line 170) for the example.

2018-10-18 04:23 UTC, acgaudette commented
Also @hobogenized there was that screen resize scaling bug.

2018-10-21 17:48 UTC, acgaudette approved these changes
Looks good. My primary point of feedback is that 2D and 3D text code is not clearly segregated. In one instance we have a generic function, in another we have a bool and conditional checks. I understand that there is a lot of shared functionality, but it is likely better to split it especially if we make further diverging changes in the future. Not too worried right now given that it appears this is not a problem at runtime i.e. the update loop.

2018-10-21 17:48 UTC, acgaudette commented on src/render.rs
> +    //binding_description: [vd::VertexInputBindingDescription; 1],
Do you need these?

2018-10-21 17:48 UTC, acgaudette commented on src/render.rs
>      // Loading shaders
```suggestion

    // Load shaders
```

2018-10-21 17:48 UTC, acgaudette commented on src/render.rs
> +            //binding_description,
Same question here.

2018-10-21 18:14 UTC, hobogenized commented
Sounds good. We'll try refactoring in the future.

2018-10-21 18:39 UTC, merged